### ISSUE TITLE
[refactor] : QA 수정 요청 사항 반영 - 유민

### ISSUE THREAD

**Issue by yuminnnnni** [KUSITMS-MOAMOA/MOAMOA_FE#129]
## Description
어떤 작업에 관한 이슈 인가요?
1차 QA 수정사항 반영

## Todo
- [x] 메모 기록 QA
- [x] 채팅 기록 QA
- [x] 회원가입 QA
- [x] [4.4] 재요청
- [x] [3.5] 재요청 로직 수정

## ETC
기타 사항
