### ISSUE TITLE
[fix] : 2차 QA 수정 요청 사항 반영 - 연아

### ISSUE THREAD

**Issue by yeona813** [KUSITMS-MOAMOA/MOAMOA_FE#165]
## Description
어떤 작업에 관한 이슈 인가요?
2차 QA 수정 요청 사항 반영 

## Todo
- [x] 홈 -> 홈(기록하기)로 변경
- [x] 홈 페이지 작성한 경험이 없을 때 높이 수정
- [x]  홈 페이지 로고 font-weight 수정
- [x] 닉네임 수정 후 로컬 스토리지 닉네임 변경
- [x] 리스트 간격 조정 
- [x] AI 역량 분석 저장 활성화 색상 변
- [x] AI 역량 분석 제목 50글자 이상 에러 메시지 추가
- [x] AI 역량 분석 내용 스크롤 설정

## ETC
기타 사항
